### ISSUE TITLE
Event Log - Error

### ISSUE THREAD

**Issue by Cyb3rN3rd777** [Ethicalrat/Evasive-Loader#1]
Hello, 

i noticed Defender doesnt seem to pick up anything however theres this error when i look at the logs, i have used the default calc.exe payload ,but there is no calc spawning is it normal ?

![Screenshot 2024-02-09 at 2 49 36 PM](https://github.com/Ethicalrat/Evasive-Loader/assets/144471817/3492b2f7-9231-4d7e-bc07-c467abd32294)

**Comment by Ethicalrat** [comment]
Hello,

No, it should open calc if you provided RC4 encrypted calc payload. Make sure to use same key to decrypt the payload and change the value of key accordingly.
